"use client";

import Image from "next/image";
import Link from "next/link";

const SECTIONS = [
  {
    id: "01",
    title: "Acceptance of terms",
    content: [
      { heading: "Agreement", body: "By accessing or using Hyphertext (\"the Service\"), you agree to be bound by these Terms of Service. If you do not agree, you must not use the Service." },
      { heading: "Age requirement", body: "You must be at least 13 years old to use Hyphertext. By using the Service, you represent that you meet this requirement." },
      { heading: "Updates", body: "We may update these terms from time to time. We'll notify you of significant changes. Continued use after changes constitutes acceptance." },
    ],
  },
  {
    id: "02",
    title: "Your account",
    content: [
      { heading: "Account responsibility", body: "You are responsible for maintaining the confidentiality of your credentials and for all activity that occurs under your account. Notify us immediately at support@hyphertext.com if you suspect unauthorised access." },
      { heading: "Accurate information", body: "You agree to provide accurate, current, and complete information when creating your account and to keep it updated." },
      { heading: "One account per person", body: "Each person may maintain one account. Creating multiple accounts to circumvent restrictions is prohibited." },
    ],
  },
  {
    id: "03",
    title: "Content and conduct",
    content: [
      { heading: "Your content", body: "You retain ownership of the content you create, upload, or publish on Hyphertext. By publishing content, you grant Hyphertext a non-exclusive, royalty-free licence to host, display, and serve that content as part of operating the Service." },
      { heading: "Prohibited content", body: "You may not publish or upload content that is illegal under Indian or applicable law; that infringes copyright, trademark, or other intellectual property rights; that contains malware, viruses, or malicious code; that constitutes spam, phishing, or deceptive practices; that harasses, threatens, or harms individuals; or that is sexually explicit, violent, or harmful to minors." },
      { heading: "Your responsibility", body: "You are solely responsible for the content you publish. Hyphertext is a platform, not an author or publisher of user content. We reserve the right to remove any content that violates these terms without notice." },
      { heading: "Respectful use", body: "You agree not to use the Service to conduct illegal activities, violate others' rights, or interfere with the normal operation of the platform." },
    ],
  },
  {
    id: "04",
    title: "Hosting and publishing",
    content: [
      { heading: "Free tier", body: "Free accounts may publish one site simultaneously. The site remains live as long as the account is active and in good standing." },
      { heading: "Pro tier", body: "Pro accounts may publish unlimited sites simultaneously for the duration of the paid subscription. When a Pro subscription expires, the account reverts to Free tier limits. Excess sites are suspended until the subscription is renewed." },
      { heading: "Service availability", body: "We aim for high availability but do not guarantee uninterrupted access. We may perform maintenance, upgrades, or modifications that temporarily affect the Service." },
      { heading: "No guaranteed uptime SLA", body: "Hyphertext is provided on a best-effort basis. We do not offer uptime SLAs or compensation for downtime for free or Pro accounts at this time." },
    ],
  },
  {
    id: "05",
    title: "Payments and subscriptions",
    content: [
      { heading: "Pricing", body: "Subscription prices are displayed at checkout. All prices are in USD unless otherwise stated. Payments are processed by Razorpay and are subject to their terms." },
      { heading: "No automatic renewal", body: "Pro subscriptions are monthly but do not auto-renew. You receive a reminder before expiry and must renew manually." },
      { heading: "Refunds", body: "We do not offer refunds for subscription payments once processed, except where required by applicable law. If you believe a charge was made in error, contact us at support@hyphertext.com within 7 days." },
      { heading: "Token purchases", body: "AI tokens purchased are non-refundable and do not expire. Token pricing may change over time; changes do not affect already-purchased tokens." },
    ],
  },
  {
    id: "06",
    title: "Intellectual property",
    content: [
      { heading: "Our platform", body: "Hyphertext, its design, codebase, and branding are the intellectual property of the Hyphertext team. You may not copy, modify, or redistribute them without express written permission." },
      { heading: "Your content", body: "We make no claim to the pages, code, images, or content you create on Hyphertext. Your creative output is yours." },
      { heading: "AI-generated content", body: "Content generated by the AI agent on your behalf is provided to you. The ownership and responsibility for AI-generated content rests with you as the user who directed its creation." },
    ],
  },
  {
    id: "07",
    title: "Termination",
    content: [
      { heading: "By you", body: "You may delete your account at any time by contacting support@hyphertext.com. Deletion is permanent and removes your data in accordance with our Privacy Policy." },
      { heading: "By us", body: "We may suspend or terminate your account if you violate these Terms, engage in fraudulent activity, or if continued operation poses a risk to other users or the platform. We will make reasonable efforts to notify you unless legally prevented from doing so." },
      { heading: "Effect of termination", body: "Upon termination, your pages will be taken offline and your access to the Service will cease. Provisions of these Terms that by nature should survive termination — including intellectual property, disclaimers, and limitation of liability — will survive." },
    ],
  },
  {
    id: "08",
    title: "Disclaimers and limitation of liability",
    content: [
      { heading: "As-is service", body: "Hyphertext is provided \"as is\" and \"as available\" without warranties of any kind, express or implied. We do not warrant that the Service will be error-free, secure, or available at all times." },
      { heading: "Limitation of liability", body: "To the maximum extent permitted by law, Hyphertext and its team shall not be liable for any indirect, incidental, consequential, or punitive damages arising from your use of the Service, even if advised of the possibility of such damages." },
      { heading: "Maximum liability", body: "Our total liability to you for any claim arising from your use of Hyphertext shall not exceed the amount you paid us in the three months preceding the claim." },
    ],
  },
  {
    id: "09",
    title: "Governing law",
    content: [
      { heading: "Jurisdiction", body: "These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of courts in Bengaluru, Karnataka, India." },
      { heading: "Dispute resolution", body: "Before initiating legal proceedings, we encourage you to contact us at support@hyphertext.com. We'll make every reasonable effort to resolve disputes amicably." },
    ],
  },
];

const ACCENT_COLORS = [
  "#C85A1A", "#1A5AC8", "#1A8A4A", "#6B3AC8",
  "#C85A1A", "#1A5AC8", "#1A8A4A", "#6B3AC8", "#C85A1A"
];

export default function TermsPage() {
  return (
    <main style={{ background: "#F4F2ED", minHeight: "100vh", fontFamily: "'DM Sans', sans-serif", color: "#111" }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,200;0,9..40,300;0,9..40,400;0,9..40,500;0,9..40,600;1,9..40,300&family=DM+Mono:wght@300;400;500&family=Playfair+Display:ital,wght@1,400&display=swap');
        *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
        ::selection { background: #111; color: #F4F2ED; }
        :root {
          --border: #D8D3C8;
          --accent: #C85A1A;
          --accent-blue: #1A5AC8;
          --accent-green: #1A8A4A;
          --accent-purple: #6B3AC8;
        }
        .nav-link {
          font-size: 1rem; font-weight: 450; color: #444;
          text-decoration: none; transition: color 0.15s;
        }
        .nav-link:hover { color: #111; }
        .policy-section {
          border-top: 1px solid var(--border);
          padding: 3.5rem 0;
          display: grid;
          grid-template-columns: 220px 1fr;
          gap: 3.5rem;
        }
        @media(max-width:700px) { .policy-section { grid-template-columns: 1fr; gap: 1.5rem; } }
      `}</style>

      {/* ── NAV ── */}
      <nav style={{
        position: "sticky", top: 0, zIndex: 100,
        background: "rgba(244,242,237,0.94)", backdropFilter: "blur(14px)",
        borderBottom: "1px solid var(--border)",
        height: "62px", display: "flex", alignItems: "center",
        justifyContent: "space-between", padding: "0 2.5rem"
      }}>
        <Link href="/" style={{ display: "flex", alignItems: "center", gap: "0.65rem", textDecoration: "none" }}>
          <Image src="/logo.png" alt="Hyphertext" width={34} height={34} style={{ borderRadius: "50%" }} />
          <span style={{ fontFamily: "'DM Mono', monospace", fontSize: "1rem", color: "#111", letterSpacing: "0.01em", fontWeight: 400 }}>
            hyphertext
          </span>
        </Link>
        <div style={{ display: "flex", alignItems: "center", gap: "2.25rem" }}>
          <Link href="/privacy" className="nav-link">Privacy</Link>
          <Link href="/auth" style={{
            background: "#111", color: "#F4F2ED",
            padding: "0.5rem 1.3rem", borderRadius: "4px",
            fontSize: "0.92rem", fontWeight: 500, textDecoration: "none"
          }}>
            Get started →
          </Link>
        </div>
      </nav>

      {/* ── HEADER ── */}
      <section style={{ borderBottom: "1px solid var(--border)" }}>
        <div style={{ background: "#111", padding: "0.55rem 2.5rem" }}>
          <span style={{ fontFamily: "'DM Mono', monospace", fontSize: "0.65rem", color: "rgba(255,255,255,0.38)", letterSpacing: "0.12em", textTransform: "uppercase", fontWeight: 400 }}>
            hyphertext · legal
          </span>
        </div>
        <div style={{ maxWidth: "960px", margin: "0 auto", padding: "5.5rem 2.5rem 4.5rem" }}>
          <div style={{
            fontFamily: "'DM Mono', monospace", fontSize: "0.78rem", fontWeight: 500,
            color: "var(--accent-blue)", letterSpacing: "0.08em", textTransform: "uppercase",
            marginBottom: "2rem", display: "flex", alignItems: "center", gap: "0.6rem"
          }}>
            <span style={{ width: "7px", height: "7px", borderRadius: "50%", background: "var(--accent-blue)", display: "inline-block" }} />
            terms of service
          </div>
          <h1 style={{ fontSize: "clamp(2.5rem, 5vw, 4.2rem)", fontWeight: 300, lineHeight: 1.07, letterSpacing: "-0.04em", color: "#111", marginBottom: "1.75rem" }}>
            Clear rules for a<br />
            <em style={{ fontFamily: "'Playfair Display', serif", fontStyle: "italic", fontWeight: 400, color: "#999" }}>fair platform.</em>
          </h1>
          <p style={{ fontSize: "1.08rem", color: "#444", fontWeight: 300, lineHeight: 1.85, maxWidth: "580px", marginBottom: "1.75rem" }}>
            These terms govern your use of Hyphertext. We've written them to be as clear and readable as possible. If you have questions, email us at support@hyphertext.com.
          </p>
          <div style={{
            fontFamily: "'DM Mono', monospace", fontSize: "0.68rem", fontWeight: 400,
            color: "#888", padding: "0.65rem 1rem",
            background: "#fff", border: "1px solid var(--border)",
            borderRadius: "4px", display: "inline-block"
          }}>
            Last updated: June 2025 · Effective immediately
          </div>
        </div>
      </section>

      {/* ── CONTENT ── */}
      <section style={{ maxWidth: "960px", margin: "0 auto", padding: "1rem 2.5rem 6rem" }}>
        {SECTIONS.map((section, idx) => (
          <div key={section.id} className="policy-section">
            <div style={{ paddingTop: "0.2rem" }}>
              <div style={{
                fontFamily: "'DM Mono', monospace", fontSize: "0.72rem", fontWeight: 500,
                color: ACCENT_COLORS[idx], letterSpacing: "0.08em",
                marginBottom: "0.6rem", display: "flex", alignItems: "center", gap: "0.4rem"
              }}>
                <span style={{ width: "5px", height: "5px", borderRadius: "50%", background: ACCENT_COLORS[idx], display: "inline-block", flexShrink: 0 }} />
                {section.id}
              </div>
              <h2 style={{ fontSize: "1rem", fontWeight: 500, color: "#222", lineHeight: 1.5, letterSpacing: "-0.01em" }}>
                {section.title}
              </h2>
            </div>
            <div style={{ display: "flex", flexDirection: "column", gap: "1.5rem" }}>
              {section.content.map((item) => (
                <div key={item.heading}>
                  <h3 style={{ fontSize: "0.96rem", fontWeight: 500, color: "#111", marginBottom: "0.45rem" }}>{item.heading}</h3>
                  <p style={{ fontSize: "0.92rem", color: "#555", fontWeight: 300, lineHeight: 1.9 }}>{item.body}</p>
                </div>
              ))}
            </div>
          </div>
        ))}

        {/* Contact */}
        <div style={{ borderTop: "1px solid var(--border)", paddingTop: "3.5rem", display: "grid", gridTemplateColumns: "220px 1fr", gap: "3.5rem" }}>
          <div>
            <div style={{
              fontFamily: "'DM Mono', monospace", fontSize: "0.72rem", fontWeight: 500,
              color: "var(--accent-green)", letterSpacing: "0.08em",
              marginBottom: "0.6rem", display: "flex", alignItems: "center", gap: "0.4rem"
            }}>
              <span style={{ width: "5px", height: "5px", borderRadius: "50%", background: "var(--accent-green)", display: "inline-block" }} />
              contact
            </div>
            <h2 style={{ fontSize: "1rem", fontWeight: 500, color: "#222" }}>Questions?</h2>
          </div>
          <div>
            <p style={{ fontSize: "0.92rem", color: "#555", fontWeight: 300, lineHeight: 1.85, marginBottom: "1rem" }}>
              For questions about these Terms, please reach out:
            </p>
            <a href="mailto:support@hyphertext.com" style={{ fontSize: "1.05rem", color: "#111", textDecoration: "underline", textUnderlineOffset: "3px", textDecorationColor: "#bbb" }}>
              support@hyphertext.com
            </a>
            <p style={{ fontSize: "0.88rem", color: "#999", fontWeight: 300, marginTop: "0.4rem" }}>Bengaluru, Karnataka, India · 560078</p>
          </div>
        </div>
      </section>

      {/* ── FOOTER (matches main page) ── */}
      <footer style={{ background: "#FAF9F5", borderTop: "1px solid var(--border)", padding: "2rem 2.5rem" }}>
        <div style={{ maxWidth: "960px", margin: "0 auto" }}>
          <div style={{
            display: "flex", alignItems: "center", justifyContent: "space-between",
            flexWrap: "wrap", gap: "1.5rem"
          }}>
            <Link href="/" style={{ display: "flex", alignItems: "center", gap: "0.65rem", textDecoration: "none" }}>
              <Image src="/logo.png" alt="Hyphertext" width={28} height={28} style={{ borderRadius: "50%" }} />
              <span style={{ fontFamily: "'DM Mono', monospace", fontSize: "0.95rem", color: "#333", letterSpacing: "0.03em", fontWeight: 400 }}>
                hyphertext
              </span>
            </Link>
            <span style={{ fontFamily: "'DM Mono', monospace", fontSize: "0.75rem", color: "#bbb", fontWeight: 400, letterSpacing: "0.02em" }}>
              © 2025 Hyphertext · Bengaluru, India
            </span>
            <div style={{ display: "flex", gap: "2rem", flexWrap: "wrap" }}>
              {[["About", "/about"], ["Pricing", "/pricing"], ["Privacy", "/privacy"], ["Terms", "/terms"]].map(([label, href]) => (
                <Link key={href} href={href}
                  style={{ fontFamily: "'DM Sans', sans-serif", fontSize: "0.88rem", color: "#888", textDecoration: "none", letterSpacing: "0.01em", fontWeight: 400, transition: "color 0.15s" }}
                  onMouseEnter={e => (e.currentTarget.style.color = "#222")}
                  onMouseLeave={e => (e.currentTarget.style.color = "#888")}
                >
                  {label}
                </Link>
              ))}
            </div>
          </div>
        </div>
      </footer>
    </main>
  );
}